name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: 🔧 ${{ matrix.host }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: true
      matrix:
        host: [ubuntu-20.04]
        python-version: [3.8.5]
    # permissions granted to the GITHUB_TOKEN secret
    # https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: false
      - name: 🖥️ Install dependencies with Poetry
        run: poetry install --verbose --no-interaction --no-ansi
      - name: ✔️ Format with black
        run: poetry run poe format
      - name: 🔎 Test with pytest
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          PLOTLY_API_KEY: ${{ secrets.PLOTLY_API_KEY }}
          PLOTLY_USERNAME: ${{ secrets.PLOTLY_USERNAME }}
        run: poetry run poe test
      - name: 🔑 Authenticate to Google Cloud using Workload Identity Federation
        # https://github.com/marketplace/actions/authenticate-to-google-cloud
        # https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md
        uses: google-github-actions/auth@v0.7.0
        with:
          # specify token_format only when troubleshooting "permission denied" errors
          # https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md#permission-denied
          token_format: 'access_token'
          # workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUM }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          workload_identity_provider: projects/1051247446620/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          # service_account: sa-dash-earthquakes@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
          service_account: sa-dash-earthquakes@prj-kitchen-sink.iam.gserviceaccount.com
      - name: Set up gcloud
        # https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment
        uses: google-github-actions/setup-gcloud@v0.6.0
      - name: Trigger a build on Cloud Build
        # the service account that submits the build to Cloud Build must have at
        # least these IAM roles:
        # roles/cloudbuild.builds.builder
        # roles/viewer
        # See also these links for examples/issues
        # https://github.com/google-github-actions/setup-gcloud/tree/main/example-workflows/cloud-build
        # https://github.com/google-github-actions/setup-gcloud/issues/62
        # https://cloud.google.com/build/docs/cloud-build-service-account#default_permissions_of_service_account
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          PLOTLY_API_KEY: ${{ secrets.PLOTLY_API_KEY }}
          PLOTLY_USERNAME: ${{ secrets.PLOTLY_USERNAME }}
        run: |-
          gcloud builds submit \
            --quiet \
            --config cloudbuild.yaml \
            --substitutions _MAPBOX_ACCESS_TOKEN=$MAPBOX_ACCESS_TOKEN,_PLOTLY_API_KEY=$PLOTLY_API_KEY,_PLOTLY_USERNAME=$PLOTLY_USERNAME
